### ISSUE TITLE
Samples won't compile

### ISSUE THREAD

**Issue by krgiddings** [OmidID/Prism.Avalonia#6]
When trying to compile the BootstrapperShell example, there is an error - "IStyledProperty could not be found"  There are also a large number of warnings.

**Comment by OmidID** [comment]
Thank you for using @krgiddings 
Because I didn't finished with Unit Test you can see many errors. 
I thinking to remove the unit test temporary. 
For the error you have please restore the packages `dotnet restore`

**Comment by krgiddings** [comment]
I tried dotnet restore,  but it still fails - what version of avalonia should it be using? (I have 8.0.2 when I look at the dependencies)

**Comment by krgiddings** [comment]
By the way,  I'm happy to get involved if you need anything doing as it would be useful for me to be able to use this with avalonia (although I'm still a relative beginner with avalonia!)
