### ISSUE TITLE
How to create a prism avalonia app

### ISSUE THREAD

**Issue by krgiddings** [OmidID/Prism.Avalonia#7]
Hi Again,

Gave up on the samples as can't get them to work and tried creating my own app.  First I started by creating a dryLoc:PrismApplication in my App.Xaml 

<dryIoc:PrismApplication x:Class="HMAIoDebuggerAv.App"
             xmlns:dryIoc="clr-namespace:Prism.DryIoc;assembly=Prism.DryIoc.Avalonia" 
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
</dryIoc:PrismApplication>

public partial class App : PrismApplication
    {
        protected override Window CreateShell()
        {
            return Container.Resolve<MainWindow>();
        }

        protected override void RegisterTypes(IContainerRegistry containerRegistry)
        {
        }
    }

However this gives me an error that App doesn't have a suitable Main method. I also can't create any windows as I get errors stating that Window and Binding cannot be found.

Is it possible you could give me a small example, that I can expand upon,  or a steps to create an avalonia prism app?

**Comment by OmidID** [comment]
Hello, Sorry I'm busy with some project and I have no time. you can see the `ModulesSample`
