### ISSUE TITLE
Error in BootStrapperShellSample

### ISSUE THREAD

**Issue by krgiddings** [OmidID/Prism.Avalonia#8]
Hi,

in the bootstrapper shell sample,  in bootstrapper.cs, IStyledProperty CreateShell() should be IAvaloniaObject CreateShell().

Regards
Keith

**Comment by OmidID** [comment]
Hello, Yes, you right. 
If you can apply changes and I'll apply pull request

**Comment by krgiddings** [comment]
Done.  You can close the other question,  as I now know what I was doing wrong (lots of things!)
